# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-06-22 21:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 22, 21, 7, 24, 818000)),
        ),
    ]
